---
language: python
services: docker

install:
  # Install ansible
  - pip install ansible molecule yamllint ansible-lint flake8

  # Check versions
  - ansible --version
  - molecule --version
  - ansible-lint --version
  - yamllint --version

script:
  # Run tests
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/