---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
  set -e
  yamllint .
  ansible-lint
  flake8
platforms:
  - name: instance
    image: docker.io/pycontribs/centos:7
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible

scenario:
  test_sequence:
    # - dependency
    - lint
    # - cleanup
    # - destroy
    # - syntax
    # - create
    # - prepare
    # - converge
    # - idempotence
    # - side_effect
    # - verify
    # - cleanup
    # - destroy
